# Generated by Django 2.0.2 on 2018-02-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturerM', '0004_auto_20180204_2026'),
        ('dealerM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.TextField()),
                ('amount', models.IntegerField()),
                ('totalCost', models.FloatField()),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealerM.Dealer')),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manufacturerM.Manufacturer')),
            ],
        ),
    ]
