# Generated by Django 2.0.2 on 2018-02-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturerM', '0005_remove_blueprint_manufacturer'),
        ('dealerM', '0003_auto_20180204_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaledeal',
            name='carName',
        ),
        migrations.AddField(
            model_name='wholesaledeal',
            name='carBlueprint',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manufacturerM.Blueprint'),
            preserve_default=False,
        ),
    ]
