# Generated by Django 2.0.2 on 2018-02-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturerM', '0005_remove_blueprint_manufacturer'),
        ('dealerM', '0004_auto_20180210_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCarInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('carBlueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturerM.Blueprint')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerM.Dealer')),
            ],
        ),
    ]
