# Generated by Django 2.0.2 on 2018-02-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerM', '0005_retailcarinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaledeal',
            name='totalCost',
        ),
        migrations.AddField(
            model_name='wholesaledeal',
            name='isRejected',
            field=models.NullBooleanField(default=True),
        ),
    ]
