# Generated by Django 2.0.2 on 2018-02-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerM', '0006_auto_20180213_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaledeal',
            name='isRejected',
            field=models.NullBooleanField(default=False),
        ),
    ]
