# Generated by Django 2.0.2 on 2018-02-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturerM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='manufacturer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manufacturerM.Manufacturer'),
            preserve_default=False,
        ),
    ]
