# Generated by Django 2.0.2 on 2018-02-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturerM', '0002_blueprint_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
