# Generated by Django 2.0.2 on 2018-02-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturerM', '0004_auto_20180204_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='manufacturer',
        ),
    ]
