# Generated by Django 2.0.2 on 2018-02-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.TextField(default='sl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.TextField(default='sl'),
            preserve_default=False,
        ),
    ]
