# Generated by Django 2.0.2 on 2018-02-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerM', '0007_auto_20180213_0712'),
        ('manufacturerM', '0005_remove_blueprint_manufacturer'),
        ('customerM', '0002_auto_20180204_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRejected', models.NullBooleanField(default=False)),
                ('carBlueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturerM.Blueprint')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerM.Customer')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerM.Dealer')),
            ],
        ),
    ]
