# Generated by Django 2.0.2 on 2018-02-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturerM', '0005_remove_blueprint_manufacturer'),
        ('customerM', '0003_retaildeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('carBlueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturerM.Blueprint')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerM.Customer')),
            ],
        ),
    ]
